name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Python_Project_Path: WeekNumber.Python

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ${{ env.Python_Project_Path }}
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install pytest pytest-cov

    - name: Test
      working-directory: ${{ env.Python_Project_Path }}
      run: pytest tests/ --tb=short --verbosity=1 --cov=. --cov-report=term-missing

